### ISSUE TITLE
Number of sites in overview list is not correct 

### ISSUE THREAD

**Issue by jowouters** [PrivacyScore/PrivacyScore#52]
The number of sites in a list, as shown in the overview page, is (in some cases) not correct.  
There does not seem to be consistency in how wrong the numbers are, although it seems to be a multiple of the numbers that are shown on the detail pages. 
 
See these 2 URLS, where you can see 2 different numbers for the same list: 
* Overview of lists: https://privacyscore.org/browse/?search=Belgium >> "Municipalities of Flanders (Belgium) " shows 1228 sites, which is certainly not correct. 
* Detail page: https://privacyscore.org/list/145/?categories=privacy%2Cssl%2Csecurity%2Cmx >> shows 307 websites (which is probably the correct number) 

Also see screenshots: 
![browse_lists_-_privacyscore](https://user-images.githubusercontent.com/1987293/45427173-80652380-b69e-11e8-9a99-d7d51ba67759.jpg)
![municipalities_of_flanders__belgium__-_privacyscore](https://user-images.githubusercontent.com/1987293/45427217-9bd02e80-b69e-11e8-9d23-21313fe081b0.jpg)

**Comment by wichmannpas** [comment]
Thanks for your report. The count was not distinct, thus counting sites multiple times if they were contained in multiple displayed lists.
