### ISSUE TITLE
How to re-edit submitted list? information missing

### ISSUE THREAD

**Issue by demarant** [PrivacyScore/PrivacyScore#59]
Once a list is successful submitted to privacyscore the user receive a message where it says
> ...If you want to edit your list later on, remember the following access token: <list_token>

However there is no information on how to re-edit the existing list and how to use the given token.

When I visit the list, there is no button or link on how to re-edit an existing list.

I looked in the FAQ page and there is no info either.

Did I miss anything? How can I re-edit a submitted list?

Thanks for the great work!

**Comment by sxxs** [comment]
Sadly, the feature to edit lists has not been implemented yet. As a workaround you can download the CSV file of a list, make the desired changes, and use it to create a new list. If you tell us which list should be replaced by your list, we can include a note forwarding users to the new list from the old list page.
