### ISSUE TITLE
Download results in different formats

### ISSUE THREAD

**Issue by finn0** [PrivacyScore/PrivacyScore#60]
Add support for download test results in different formats JSON, XML, plain text etc.

**Comment by finn0** [comment]
@muellermartin , I mean to say download whole contain as json file directly from browser by additional clicking on a button `https://privacyscore.org/site/[site-id]/json/` page. Yes, I can copy that data and paste it newly created file in my system but it's very annoying. Or, show test results like way https://wtfismyip.com/json so, I can perform curl and download data.

**Comment by malexmave** [comment]
There is an (undocumented) feature to get raw JSON by appending `?raw` to the URL. However, please note that the format of the JSON will likely change without notice in the future, so don't consider this a stable API.

**Comment by finn0** [comment]
@malexmave , gotcha. What about other data formats? Can a make a pull request for that?

**Comment by malexmave** [comment]
We'd prefer to stick to JSON right now. Converters for other formats make it harder for us to change our backend, which is going to go through some changes in the future. If your application requires a different input, there should be enough converters for JSON => X available to do this client-side. Or is there any specific reason this should be supported natively by our backend?

**Comment by finn0** [comment]
No, nothing specific.
