### ISSUE TITLE
PS-Runner for donating bandwidth and processing speed to the project

### ISSUE THREAD

**Issue by JonasDralle** [PrivacyScore/PrivacyScore#66]
Hi. I have some spare hardware which runs 24/7 and does on-and-off-work for me.
Is it possible to have a PrivacyScore-runner on this machine?

Like some simple client that gets a workload from your server and then transmits the results back?

**Comment by malexmave** [comment]
Thanks for the offer! We've been considering something like this for a while. At the moment, we are reworking how the system runs on the backend, and thus don't have a stable API for such a functionality. We also greatly depend on having SSH access to all machines (for deployment) and all machines being at least somewhat trusted (read and write access to the database, ...). So, re-engineering PrivacyScore to support semi-trusted external clients to submit data without allowing them to change arbitrary parts of the database would be a non-trivial task.

In addition, running everything on-premise at universities makes handling the inevitable abuse messages from an overzealous IDS easier - some systems interpret our scans as attacks and send automated abuse reports, which you (probably) don't want to deal with.

So, thank you again for the kind offer. We're keeping the idea in the back of our minds and if the scan backend is stable (in the sense of "does not change frequently"), we may get back to it if we find someone who wants to implement the interfaces for it.
